name: Deploy Vite Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

      - name: Set up Node
        # actions/setup-node@v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f5252474591e5120a122ac 
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        # actions/upload-pages-artifact@v3.0.1
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dee46217193b 
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # actions/deploy-pages@v4.0.4
        uses: actions/deploy-pages@9830c25841c22caf690be562d7735d46920e1a2d